generic-service:
  nameOverride: hmpps-activities-management-orchestrator-api
  productId: "DPS028" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-activities-management-orchestrator-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: activities-orchestrator-api-cert

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    APPLICATIONINSIGHTS_STATSBEAT_DISABLED: "true"
    JAVA_TOOL_OPTIONS: "$(JAVA_PROXY_TOOL_OPTIONS) -XX:+ExitOnOutOfMemoryError -XX:MaxRAMPercentage=50.0"

  namespace_secrets:
    hmpps-activities-management-orchestrator-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-activities-management-orchestrator-api-client-creds:
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    hmpps-envoy-https-proxy-env:
      HTTP_PROXY: "HTTP_PROXY"
      HTTPS_PROXY: "HTTPS_PROXY"
      NO_PROXY: "NO_PROXY"
      JAVA_PROXY_TOOL_OPTIONS: "JAVA_PROXY_TOOL_OPTIONS"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-activities-management-orchestrator-api
