server.port: 8082

hmpps:
  auth:
    url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

activities:
  api:
    url: "http://localhost:8080"

prisoner-search:
  api:
    url: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    timeout: 10s
