server.port: 8082

hmpps:
  auth:
    url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

activities-management:
  api:
    url: "https://activities-api-dev.prison.service.justice.gov.uk"

prisoner-search:
  api:
    url: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    timeout: 10s
