### Gets event data for review
// @no-log
< {%
    request.variables.set("prisonCode", "LEI")
%}

GET {{ baseUrl }}/event-review/prison/{{prisonCode}}?date=2023-09-25
Authorization: Bearer <<bearerToken>>
Content-Type: application/json

### Get prisoner number by name
GET {{ baseUrl }}/prisoner/prisoner-number-by-name?prisonerForename=JOE
Authorization: Bearer <<bearerToken>>
Content-Type: application/json

{ "prisonerNumbers": ["A1234AA"] }