---
# Per environment values which override defaults in hmpps-activities-management-orchestrator-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: activities-orchestrator-api-dev.prison.service.justice.gov.uk
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecAuditEngine On
      SecRuleEngine DetectionOnly
      SecDefaultAction "phase:2,pass,log,tag:github_team=activities-and-appointments,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    ACTIVITIES_API_URL: "https://activities-api-dev.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    SPRINGDOC_API-DOCS_ENABLED: "true"
    SPRINGDOC_SWAGGER-UI_ENABLED: "true"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-activities-management-dev
